### ISSUE TITLE
Ansible to EC2

### ISSUE THREAD

**Issue by ronaldpetty** [RX-M/scarif#1]

**Comment by ronaldpetty** [comment]
* create a VM
* install Ansible - http://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu
* install ec2 module requirements
  * pip - sudo apt-get install python python-pip -y
  * boto - pip install boto boto3
* install awscli
  * pip install awscli
* AWS access keys
  * configure keys via awscli
  * export AWS_ACCESS_KEY_ID
  * export AWS_SECRET_ACCESS_KEY
* ec2 dynamic inventory - http://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script
  * curl -LO https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ec2.ini
  * curl -LO https://raw.github.com/ansible/ansible/devel/contrib/inventory/ec2.py
  * chmod 500 ec2.py
  * ./ec2.py --list

export ANSIBLE_HOSTS=$(pwd)/ec2.py
export EC2_INI_PATH=$(pwd)/ec2.ini
ansible all -m ping

```
user@ubuntu:~$ cat hosts 
[local]
localhost
user@ubuntu:~$
```

```
user@ubuntu:~$ cat ron.py 
- hosts: local
  connection: local
  gather_facts: no
  tasks:
  - name: create a new ec2 key pair, returns generated private key
    ec2_key:
      name: my_keypair
user@ubuntu:~$
```

`ansible-playbook -i hosts ron.py`
